[[custom_groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ”® è´Ÿè½½å‡è¡¡", ".*"]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 150

[[custom_groups]]
name = "ğŸ”® è´Ÿè½½å‡è¡¡"
type = "load-balance"
strategy = "round-robin"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 150
